# =============================================================================
# 37_tables.R -- CANONICAL TABLES (CSV + TEX) AND METHODS NUMBERS
#
# Main paper:  table_main_results, table_sample_characteristics,
#              table_selected_aquifers
# SI:          table_si_h1_h2_robustness, table_si_localization_robustness,
#              table_si_aquifer_stability, table_si_matching_overlap,
#              table_si_sample_flow
# Plus:        methods_numbers.csv / methods_numbers.tex
# =============================================================================

.args <- commandArgs(FALSE)
.f <- sub("^--file=", "", .args[grepl("^--file=", .args)])
.root <- if (length(.f)) dirname(normalizePath(.f[1])) else getwd()
if (!exists("CFG")) source(file.path(.root, "31_config.R"))
if (!exists("run_specification")) source(file.path(CFG$root, "32_core.R"))
if (is.null(.log$path)) log_open(CFG$log_file)
cfg <- CFG
t0 <- Sys.time()

main <- readRDS(file.path(cfg$cache_dir, "main_objects.rds"))
rob  <- readRDS(file.path(cfg$cache_dir, "robustness_objects.rds"))
summ <- readRDS(file.path(cfg$cache_dir, "summaries.rds"))
pref <- main$pref; d <- pref$data; h3 <- main$h3; ident <- main$ident
dir.create(cfg$out_dir, showWarnings = FALSE, recursive = TRUE)

fmt <- function(x, dg = 3) {
  ifelse(is.na(x), "",
         ifelse(abs(x - round(x)) < 1e-9 & abs(x) >= 1000,
                formatC(round(x), format = "d", big.mark = ","),
                formatC(signif(x, dg), format = "fg", flag = "#")))
}
tex_escape <- function(x) gsub("%", "\\\\%", gsub("_", "\\\\_", gsub("&", "\\\\&", x)))
write_pair <- function(df, name, tex_digits = 3, caption = NULL) {
  csv_path <- file.path(cfg$out_dir, paste0(name, ".csv"))
  readr::write_csv(as.data.frame(df), csv_path)
  # minimal LaTeX tabular
  df2 <- df %>% mutate(across(where(is.numeric), ~ fmt(.x, tex_digits)),
                       across(where(is.logical), ~ ifelse(is.na(.x), "", ifelse(.x, "yes", "no"))),
                       across(everything(), as.character),
                       across(everything(), ~ tex_escape(replace_na(.x, ""))))
  al <- paste(rep("l", ncol(df2)), collapse = "")
  lines <- c(
    sprintf("%% Auto-generated by 37_tables.R on %s -- do not edit.", Sys.Date()),
    sprintf("\\begin{tabular}{%s}", al), "\\hline",
    paste(paste(tex_escape(names(df2)), collapse = " & "), "\\\\"), "\\hline",
    paste(apply(df2, 1, paste, collapse = " & "), "\\\\"),
    "\\hline", "\\end{tabular}")
  writeLines(lines, file.path(cfg$out_dir, paste0(name, ".tex")))
  say("  wrote ", name, ".csv/.tex\n")
}

# =============================================================================
# MAIN: table_main_results
# =============================================================================
mrow <- function(hyp, s, unit, alt, mde80 = NA, mde90 = NA, mde_src = NA) {
  bind_rows(
    tibble(hypothesis = hyp, term = "transboundary contrast", unit = unit,
           estimate = s$estimate, ci90_low = s$ci90_low, ci90_high = s$ci90_high,
           one_sided_bound95 = if (alt == "less") s$ci90_high else if (alt == "greater") s$ci90_low else NA_real_,
           p_one_sided = s$p_one, p_one_source = s$p_one_source,
           p_two_sided_cr2 = s$p_cr2, p_two_sided_wild = s$p_wild,
           wcb_ci_low = s$wcb_lo, wcb_ci_high = s$wcb_hi,
           mde80 = mde80, mde90 = mde90, uncertainty_source = s$se_source,
           tau2 = s$tau2),
    tibble(hypothesis = hyp,
           term = if (grepl("^H2", hyp)) "intercept (placebo-type diagnostic)"
                  else "matched domestic baseline",
           unit = unit,
           estimate = s$baseline, ci90_low = s$baseline_lo,
           ci90_high = s$baseline_hi,
           p_two_sided_cr2 = s$baseline_p,
           uncertainty_source = "CR2 country-clustered SE"))
}
tmain <- bind_rows(
  mrow("H1: depletion level", pref$h1, "mm/yr", "greater",
       mde80 = main$mde80, mde90 = main$mde90),
  mrow("H2: borderward gradient", pref$h2, "Fisher z", "less"))
write_pair(tmain, "table_main_results", 4)

# =============================================================================
# MAIN: table_sample_characteristics
# =============================================================================
sd_ <- summ$seg_desc; dd_ <- summ$dist_desc
tsc <- bind_rows(
  tibble(characteristic = "aquifer-country segments",
         transboundary = sd_$n_segments[sd_$group == "transboundary"],
         domestic = sd_$n_segments[sd_$group == "domestic"]),
  tibble(characteristic = "physical aquifers",
         transboundary = sd_$n_aquifers[sd_$group == "transboundary"],
         domestic = sd_$n_aquifers[sd_$group == "domestic"]),
  tibble(characteristic = "countries",
         transboundary = sd_$n_countries[sd_$group == "transboundary"],
         domestic = sd_$n_countries[sd_$group == "domestic"]),
  tibble(characteristic = "observation wells",
         transboundary = sd_$wells_total[sd_$group == "transboundary"],
         domestic = sd_$wells_total[sd_$group == "domestic"]),
  tibble(characteristic = "median wells per segment",
         transboundary = sd_$wells_median[sd_$group == "transboundary"],
         domestic = sd_$wells_median[sd_$group == "domestic"]),
  tibble(characteristic = "median well-to-border distance (km)",
         transboundary = dd_$median_dist_km[dd_$group == "transboundary"],
         domestic = dd_$median_dist_km[dd_$group == "domestic"]),
  tibble(characteristic = "share of wells within 100 km of a border",
         transboundary = dd_$share_within_100km[dd_$group == "transboundary"],
         domestic = dd_$share_within_100km[dd_$group == "domestic"]),
  tibble(characteristic = "effective sample size (overlap weights)",
         transboundary = main$balance_summary$ess_treated_ato,
         domestic = main$balance_summary$ess_control_ato))
write_pair(tsc, "table_sample_characteristics", 4)

# =============================================================================
# MAIN: table_selected_aquifers
# =============================================================================
sel <- ident$table %>% filter(selected) %>%
  left_join(h3$scatter %>% select(.gid, exc_level, exc_gradient, pattern),
            by = ".gid") %>%
  left_join(d %>% transmute(unit_id, CC,
                            share_10km = share_within_10km,
                            share_50km = share_within_50km,
                            share_100km = share_within_100km),
            by = c(".gid" = "unit_id")) %>%
  transmute(segment = label_txt, country = CC, wells = n_wells,
            share_wells_within_10km = share_10km,
            share_wells_within_50km = share_50km,
            share_wells_within_100km = share_100km,
            raw_excess_depletion_mm_yr = dep_vs_domestic,
            raw_excess_gradient_z = grad_vs_domestic,
            shrunken_excess_depletion_mm_yr = exc_level,
            shrunken_excess_gradient_z = exc_gradient,
            quadrant = pattern, rank_raw,
            selection_top_k_raw = raw_top,
            selection_consistent_all_paths = consistent)
write_pair(sel, "table_selected_aquifers", 3)

# =============================================================================
# SI: table_si_h1_h2_robustness  (blocks A and B)
# =============================================================================
tAB <- summ$h2_rob %>%
  left_join(summ$h1_rob %>%
              select(specification, h1_estimate, h1_ci90_low, h1_ci90_high,
                     h1_p_one, h1_wcb_lo, h1_wcb_hi,
                     h1_wcb_bound_one, h1_wcb_bound_one_alt,
                     uncertainty_source, h1_mde80, h1_mde90),
            by = "specification") %>%
  relocate(family, specification, estimand)
write_pair(tAB, "table_si_h1_h2_robustness", 4)

# =============================================================================
# SI: table_si_registry_display  (presentation form of the registry table)
#
# The machine-readable registry table above carries every exported field. This
# is the version that goes into the SI.
#
# WHICH INTERVAL IS PRINTED, AND WHY. With 19 country clusters the reported p_1
# is the directional wild cluster bootstrap p-value, so the interval beside it
# is the bootstrap interval, obtained by inverting the same test. A CR2 interval
# in that position can contradict its own p-value and does: the preferred row
# has H2 p_1 = 0.045 against a CR2 90% interval of [-0.160, 0.002] that contains
# zero, while the bootstrap interval for that row is [-0.124, -0.002].
#
# Two intervals are printed because they answer different questions. The 90% CI
# is two-sided and is there for transparency; it can still disagree with a
# one-sided p_1 near the boundary, because a two-sided interval and a one-sided
# test are not the same statement -- Conley cutoff 5 km is the case in this
# registry (p_1 = 0.047, two-sided bootstrap p = 0.102). The one-sided 95% bound
# inverts the directional test itself, so it excludes zero exactly when
# p_1 < 0.05, in every row, by construction. It is the bar plotted in Fig. 2A.
#
# The five rows with no H1 entry are the overrides that alter only the gradient
# outcome; their H1 result is the preferred estimate by construction and is left
# blank rather than repeated.
#
# NOTE ON THE MDE COLUMNS. MDE = (z_{1-alpha_one} + z_power) * SE, from the CR2
# standard error. It is normal-theory, while the CR2 degrees of freedom in this
# registry run from 0.3 to 4.5, so the MDE is not a rescaling of any interval in
# the same row and is the more optimistic of the pair. Read it as a statement
# about the design's power. The country-fixed-effects row is the extreme case:
# MDE_80 = 53 mm/yr on degrees of freedom near one.
# =============================================================================

# Row order, short labels and group rules for the SI. Keyed on the registry's
# own `specification` string, so a renamed specification fails loudly below
# rather than silently dropping out of the table.
SI_DISPLAY <- tibble::tribble(
  ~grp, ~specification,                                                   ~label,
  0, "Preferred specification (ATO)",                                     "Preferred specification (ATO)",
  1, "Country fixed effects (within-country identification)",             "Country fixed effects",
  1, "ATT estimand, nearest-neighbour matching (different estimand)",     "ATT estimand, nearest-neighbour matching",
  2, "Spearman rank correlation for H2",                                  "Spearman rank correlation for H2",
  2, "H2 as physical slope, mm/yr/km (table only)",                       "H2 as physical slope, mm/yr/km",
  2, "Robust (Huber M) first-stage level (approx. spatial SE)",           "Robust (Huber M) first-stage level",
  2, "Trimmed-mean first-stage level (approx. spatial SE)",               "Trimmed-mean first-stage level",
  2, "Stricter distance-variation screen (SD >= 10 km)",                  "Stricter distance-variation screen (SD$\\geq$10)",
  2, "Wells within 0-100 km only (support diagnostic)",                   "Wells within 0--100 km only",
  2, "Empirical common distance support (45-365 km)",                     "Empirical common distance support (45--365 km)",
  3, "Conley cutoff 5 km",                                                "Conley cutoff 5 km",
  3, "Conley cutoff 25 km",                                               "Conley cutoff 25 km",
  3, "Conley cutoff 50 km",                                               "Conley cutoff 50 km",
  3, "Effective sample size n/rho^0",                                     "Effective sample size $n/\\rho^{0}$",
  3, "Effective sample size n/rho^1",                                     "Effective sample size $n/\\rho^{1}$",
  3, "Dense-segment Conley subsample, seed 2",                            "Dense-segment Conley subsample, seed 2",
  3, "Dense-segment Conley subsample, seed 3",                            "Dense-segment Conley subsample, seed 3",
  3, "Dense-segment Conley subsample, seed 4",                            "Dense-segment Conley subsample, seed 4",
  3, "Dense-segment Conley subsample, seed 5",                            "Dense-segment Conley subsample, seed 5",
  3, "Dense-segment Conley subsample, seed 6",                            "Dense-segment Conley subsample, seed 6",
  4, "No variance winsorisation",                                         "No variance winsorisation",
  4, "Variance winsorisation at 5th/95th",                                "Variance winsorisation at 5th/95th",
  4, "No segment random effect",                                          "No segment random effect",
  4, "Minimum 50 wells per segment",                                      "Minimum 50 wells per segment",
  4, "Minimum 100 wells per segment",                                     "Minimum 100 wells per segment",
  4, "Unadjusted outcome model (~ 1 + TBn)",                              "No Covariate",
  4, "Augmented covariate set (+ precipitation)",                         "Augmented covariate set (+ precipitation)",
  4, "ATO-weighted, equal segment information",                           "ATO-weighted, equal segment information",
  4, "Exclude river-border segments",                                     "Exclude river-border segments")

## Augmented specifications (well-level regressions, governance proxy, natural
## water-table depth) are estimated in 34 alongside the registry but are not
## registry entries -- they refit the design on a frame the registry cannot
## express. They are appended here on the same columns, and named in the
## display table only when they were actually produced, for the same reason as
## the nocrossriver row below.
if (!is.null(rob$augmented) && nrow(rob$augmented)) {
  tAB <- dplyr::bind_rows(tAB, rob$augmented)
  .aug_labels <- c(
    "Well-level regression, random intercepts"        = "Well-level regression, random intercepts",
    "Well-level regression, country fixed effects"    = "Well-level regression, country fixed effects",
    "Augmented covariate set (+ governance proxy)"    = "Augmented covariate set (+ governance proxy)",
    "Augmented covariate set (+ natural water-table depth)" =
      "Augmented covariate set (+ natural water-table depth)")
  for (.s in intersect(names(.aug_labels), tAB$specification))
    SI_DISPLAY <- tibble::add_row(SI_DISPLAY, grp = 4, specification = .s,
                                  label = unname(.aug_labels[.s]))
}

## The nocrossriver row exists only when 1_data/river_crossings_by_unit.csv
## was present when 34_run_robustness.R built the registry (the row is skipped
## otherwise), so it is appended conditionally rather than named above --
## naming it unconditionally would turn a missing optional input into a stop().
## The label carries the discharge floor through from the registry string, so
## a re-classification at a different Q cannot leave a stale "10" in print.
.ncr_spec <- grep("^Exclude aquifers with a border-crossing river",
                  tAB$specification, value = TRUE)
if (length(.ncr_spec) == 1L)
  SI_DISPLAY <- tibble::add_row(SI_DISPLAY, grp = 4, specification = .ncr_spec,
    label = sub("\\(Q >= ([0-9.]+) m3/s\\)",
                "(Q$\\\\geq$\\1~m$^3$\\\\,s$^{-1}$)", .ncr_spec))

.missing <- setdiff(SI_DISPLAY$specification, tAB$specification)
if (length(.missing))
  stop("SI_DISPLAY names specifications that are not in the registry: ",
       paste(.missing, collapse = " | "))
# A registry row left out of the display table is a choice, not an accident, so
# it is named in the log every run rather than quietly disappearing.
.dropped <- setdiff(tAB$specification, SI_DISPLAY$specification)
if (length(.dropped))
  sayf("  registry rows not shown in table_si_registry_display: %s\n",
       paste(.dropped, collapse = " | "))

si_num <- function(x, dg)
  ifelse(is.na(x), "", formatC(x, format = "f", digits = dg))
si_ci <- function(lo, hi, dg)
  ifelse(is.na(lo) | is.na(hi), "",
         sprintf(paste0("[%.", dg, "f, %.", dg, "f]"), lo, hi))
# "greater" is a lower bound, "less" an upper bound. Printing the direction with
# the number keeps the two hypotheses from being read as the same object.
si_bound <- function(b, alt, dg)
  ifelse(is.na(b) | is.na(alt), "",
         sprintf(paste0("$%s$ %.", dg, "f"),
                 ifelse(alt == "greater", ">", "<"), b))
si_bold <- function(x) ifelse(nzchar(x), sprintf("\\textbf{%s}", x), x)

tDISP <- SI_DISPLAY %>%
  left_join(tAB, by = "specification") %>%
  transmute(grp, label, specification,
            h1_estimate, h1_wcb_lo, h1_wcb_hi,
            h1_wcb_bound_one, h1_wcb_bound_one_alt,
            h1_p_one, h1_mde80, h1_mde90,
            h2_estimate, h2_wcb_lo, h2_wcb_hi,
            h2_wcb_bound_one, h2_wcb_bound_one_alt, h2_p_one)
readr::write_csv(as.data.frame(tDISP),
                 file.path(cfg$out_dir, "table_si_registry_display.csv"))

.cell <- with(tDISP, cbind(
  label,
  si_num(h1_estimate, 1),
  si_ci(h1_wcb_lo, h1_wcb_hi, 0),
  si_bound(h1_wcb_bound_one, h1_wcb_bound_one_alt, 0),
  si_num(h1_p_one, 3),
  si_num(h1_mde80, 0),
  si_num(h1_mde90, 0),
  si_num(h2_estimate, 3),
  si_ci(h2_wcb_lo, h2_wcb_hi, 3),
  si_bound(h2_wcb_bound_one, h2_wcb_bound_one_alt, 3),
  si_num(h2_p_one, 3)))
.cell[tDISP$grp == 0, ] <- si_bold(.cell[tDISP$grp == 0, ])
.rows <- paste(apply(.cell, 1, paste, collapse = " & "), "\\\\")
# A rule between families, and after the preferred row that anchors the table.
.brk <- which(diff(tDISP$grp) != 0)
for (i in rev(.brk))
  .rows <- append(.rows, c("\\addlinespace[3pt]", "\\hline"), after = i)

writeLines(c(
  sprintf("%% Auto-generated by 37_tables.R on %s -- do not edit.", Sys.Date()),
  "\\setlength{\\tabcolsep}{4pt}",
  "\\resizebox{\\ifdim\\width>\\linewidth\\linewidth\\else\\width\\fi}{!}{%",
  "\\begin{tabular}{lrcrrrr|rcrr}",
  "\\hline",
  paste("& \\multicolumn{6}{c|}{H1: mean depletion (mm yr$^{-1}$)}",
        "& \\multicolumn{4}{c}{H2: depletion--distance gradient} \\\\"),
  paste("Specification & est. & 90\\% CI & bound$_{95}$ & $p_1$",
        "& MDE$_{80}$ & MDE$_{90}$ & est. & 90\\% CI & bound$_{95}$ & $p_1$ \\\\"),
  "\\hline",
  .rows,
  "\\hline", "\\end{tabular}}"),
  file.path(cfg$out_dir, "table_si_registry_display.tex"))
say("  wrote table_si_registry_display.csv/.tex\n")

# =============================================================================
# SI Table S1: table_si_wells_sumstats
#
# Segment-level summary statistics, median [Q1, Q3], for the four groups the
# preferred design actually distinguishes. The design targets the Average
# Treatment effect in the Overlap population, so BOTH arms carry weights
# (w = 1-e for transboundary segments, w = e for domestic ones); reporting
# each arm unweighted and ATO-weighted is what makes the reweighting legible.
#
# This replaces a hand-built table that predated the current sample and the
# move to overlap weights. That table reported 637 domestic segments against
# the 654 used everywhere else, and carried four variables the current
# configuration does not have: segment area, distance to the nearest major
# road, the GAEZ soil/terrain suitability index and TerraClimate PET. Those
# rows are not reconstructed here because the pipeline has no source for them.
# =============================================================================

# Weighted quantiles on the weighted ECDF. With equal weights this reduces to
# the ordinary sample quantile, so both column families use one code path.
wquantile <- function(x, w, probs) {
  ok <- is.finite(x) & is.finite(w) & w > 0
  x <- x[ok]; w <- w[ok]
  if (!length(x)) return(rep(NA_real_, length(probs)))
  o <- order(x); x <- x[o]; w <- w[o]
  cw <- cumsum(w) / sum(w)
  out <- numeric(length(probs))
  for (k in seq_along(probs)) {
    i <- which(cw >= probs[k])[1L]
    out[k] <- if (is.na(i)) x[length(x)] else x[i]
  }
  out
}

mqi <- function(x, w) {
  q <- wquantile(x, w, c(0.25, 0.50, 0.75))
  paste0(fmt(q[2], 3), " [", fmt(q[1], 3), ", ", fmt(q[3], 3), "]")
}

# The segment frame keeps the minimum, SD and range of well-to-border distance
# but not its mean, so that one variable is taken from the well frame here
# rather than added to the cached segment build.
.wf <- fs_wells(cfg) %>%
  group_by(unit_id) %>%
  summarise(D_border = mean(dist_LB_km, na.rm = TRUE), .groups = "drop")
dS <- d %>% left_join(.wf, by = "unit_id")

.sv_var <- c("n", "urbkHaKm2", "CS_max", "prec_mm",
             "beta_0", "D_border", "LB_river")
.sv_lab <- c("$N_w$ observation wells per segment",
             "$UC$ urban cover (kha km$^{-2}$)",
             "$CSI$ crop suitability index (1--10,000)",
             "$PREC$ annual precipitation (mm yr$^{-1}$)",
             "$GWD$ segment mean depletion (mm yr$^{-1}$)",
             "$D_border$ mean well-to-border distance (km)",
             "$P_LBRiv$ share of wells whose nearest border is a river")

.col_nm <- c("Domestic", "Domestic (ATO)", "Transboundary", "Transboundary (ATO)")
.col_tb <- c(0L, 0L, 1L, 1L)
.col_wt <- c(FALSE, TRUE, FALSE, TRUE)

.ess <- function(w) sum(w)^2 / sum(w^2)

.cells <- matrix("", nrow = length(.sv_var) + 2L, ncol = length(.col_nm))
for (j in seq_along(.col_nm)) {
  sub <- dS[dS$TBn == .col_tb[j], , drop = FALSE]
  wj  <- if (.col_wt[j]) sub$w_ato else rep(1, nrow(sub))
  .cells[1L, j] <- as.character(nrow(sub))
  for (i in seq_along(.sv_var))
    .cells[i + 1L, j] <- mqi(sub[[.sv_var[i]]], wj)
  .cells[length(.sv_var) + 2L, j] <-
    if (.col_wt[j]) fmt(.ess(wj), 4) else as.character(nrow(sub))
}

tS1 <- data.frame(
  Variable = c("$N$ aquifer--country segments", .sv_lab,
               "effective sample size (segments)"),
  .cells, stringsAsFactors = FALSE, check.names = FALSE)
names(tS1) <- c("Variable", .col_nm)

# Guard rails: the table must describe the same sample the results do.
stopifnot(nrow(dS) == nrow(d),
          sum(dS$TBn == 1) == sum(d$TBn == 1),
          all(is.finite(dS$w_ato)))
write_pair(tS1, "table_si_wells_sumstats", 3)

# =============================================================================
# SI: table_si_localization_robustness  (block C)
# =============================================================================
tC <- bind_rows(rob$locC$table,
                rob$locC$loo %>% mutate(specification =
                                          paste0("LOO: ", specification)))
write_pair(tC, "table_si_localization_robustness", 4)

# =============================================================================
# SI: table_si_aquifer_stability  (block D; every TBA segment)
# =============================================================================
stab <- rob$h3_bootstrap$stability
selstab <- rob$selection_stability %>%
  group_by(.gid) %>%
  summarise(n_family_specs = n_distinct(family_spec),
            n_selected_in = sum(selected),
            share_fast_borderward = mean(pattern == "fast + borderward",
                                         na.rm = TRUE),
            .groups = "drop")
tD <- h3$scatter %>%
  left_join(d %>% transmute(unit_id, CC,
                            share_10km = share_within_10km,
                            share_50km = share_within_50km,
                            share_100km = share_within_100km),
            by = c(".gid" = "unit_id")) %>%
  left_join(ident$raw %>% select(.gid, dep_vs_domestic, grad_vs_domestic,
                                 rank_raw), by = ".gid") %>%
  left_join(ident$table %>% select(.gid, selected, consistent, n_criteria),
            by = ".gid") %>%
  left_join(stab, by = c(".gid" = "gid")) %>%
  left_join(selstab, by = ".gid") %>%
  transmute(segment = label_txt, country = CC, wells = n_wells,
            share_10km, share_50km, share_100km,
            h1_excess_raw = dep_vs_domestic, h2_excess_raw = grad_vs_domestic,
            h1_excess_shrunken = exc_level, h2_excess_shrunken = exc_gradient,
            quadrant = pattern, rank_raw,
            rank_level_shrunken = rank_level,
            rank_gradient_shrunken = rank_gradient,
            boot_top10_level_freq = top10_level_cond,
            boot_top10_gradient_freq = top10_gradient_cond,
            n_family_specs, n_selected_in_family_specs = n_selected_in,
            share_family_specs_fast_borderward = share_fast_borderward,
            selected = coalesce(selected, FALSE),
            selection_consistent = coalesce(consistent, FALSE),
            selection_n_criteria = n_criteria) %>%
  arrange(desc(selected), rank_raw)
write_pair(tD, "table_si_aquifer_stability", 3)

# =============================================================================
# SI: table_si_matching_overlap
# =============================================================================
tmo <- main$balance %>%
  mutate(across(where(is.numeric), ~ round(.x, 4))) %>%
  bind_rows(tibble(covariate = "effective control sample size (segments)",
                   in_ps = NA, unweighted = summ$seg_desc$n_segments[
                     summ$seg_desc$group == "domestic"],
                   matched = main$balance_summary$ess_control_att,
                   ATO = main$balance_summary$ess_control_ato))
write_pair(tmo, "table_si_matching_overlap", 4)

# =============================================================================
# SI: table_si_sample_flow
# =============================================================================
write_pair(summ$sample_flow, "table_si_sample_flow", 6)

# =============================================================================
# methods_numbers.csv / .tex
# =============================================================================
mn <- summ$methods_numbers
readr::write_csv(as.data.frame(mn), file.path(cfg$out_dir, "methods_numbers.csv"))
tex_val <- function(v, unit) {
  if (is.na(v)) return(tex_escape(unit))   # text-valued entries carry unit text
  if (abs(v - round(v)) < 1e-9) formatC(round(v), format = "d", big.mark = "{,}")
  else sub("\\.?0+$", "", formatC(v, format = "f", digits = 4))
}
writeLines(c(
  "% Auto-generated by 37_tables.R -- do not edit by hand.",
  "% \\input{methods_numbers.tex} in the preamble, then use e.g. \\nWellsFinal.",
  sprintf("\\newcommand{\\%s}{%s}", mn$key,
          mapply(tex_val, mn$value, mn$unit))),
  file.path(cfg$out_dir, "methods_numbers.tex"))
say("  wrote methods_numbers.csv/.tex\n")

sayf("37_tables.R done in %.1f min.\n",
     as.numeric(difftime(Sys.time(), t0, units = "mins")))
