# =============================================================================
# make_table_s1.R -- BUILD SI TABLE S1 ON ITS OWN
#
#   Rscript make_table_s1.R          # from the wells module folder
#
# Table S1 is a description of the preferred design's segment frame. It needs
# main_objects.rds (written by 33_run_main.R) and the well frame, and nothing
# from 34, 35 or 36 -- so it can be built in seconds without waiting for the
# robustness blocks to finish.
#
# This is a convenience entry point. The same block runs inside 37_tables.R as
# part of the normal pipeline; both write the identical files.
# =============================================================================

.args <- commandArgs(FALSE)
.f <- sub("^--file=", "", .args[grepl("^--file=", .args)])
.root <- if (length(.f)) dirname(normalizePath(.f[1])) else getwd()
if (!exists("CFG")) source(file.path(.root, "31_config.R"))
if (!exists("run_specification")) source(file.path(CFG$root, "32_core.R"))
cfg <- CFG

.mp <- file.path(cfg$cache_dir, "main_objects.rds")
if (!file.exists(.mp))
  stop("main_objects.rds not found at ", .mp,
       "\n  Run 33_run_main.R first.")
main <- readRDS(.mp)
pref <- main$pref
d <- pref$data
dir.create(cfg$out_dir, showWarnings = FALSE, recursive = TRUE)

# Helpers normally supplied by 37_tables.R -----------------------------------
fmt <- function(x, dg = 3) {
  ifelse(is.na(x), "",
         ifelse(abs(x - round(x)) < 1e-9 & abs(x) >= 1000,
                formatC(round(x), format = "d", big.mark = ","),
                formatC(signif(x, dg), format = "fg", flag = "#")))
}
tex_escape <- function(x) gsub("%", "\\\\%", gsub("_", "\\\\_", gsub("&", "\\\\&", x)))
write_pair <- function(df, name, tex_digits = 3, caption = NULL) {
  readr::write_csv(as.data.frame(df), file.path(cfg$out_dir, paste0(name, ".csv")))
  df2 <- as.data.frame(lapply(df, function(z) tex_escape(as.character(z))),
                       stringsAsFactors = FALSE, check.names = FALSE)
  al <- paste(rep("l", ncol(df2)), collapse = "")
  lines <- c(
    sprintf("%% Auto-generated by make_table_s1.R on %s -- do not edit.", Sys.Date()),
    sprintf("\\begin{tabular}{%s}", al), "\\hline",
    paste(paste(tex_escape(names(df2)), collapse = " & "), "\\\\"), "\\hline",
    paste(apply(df2, 1, paste, collapse = " & "), "\\\\"),
    "\\hline", "\\end{tabular}")
  writeLines(lines, file.path(cfg$out_dir, paste0(name, ".tex")))
  say("  wrote ", name, ".csv/.tex\n")
}

say("\n############ SI Table S1 ############\n")

# =============================================================================
# SI Table S1: table_si_wells_sumstats
#
# Segment-level summary statistics, median [Q1, Q3], for the four groups the
# preferred design actually distinguishes. The design targets the Average
# Treatment effect in the Overlap population, so BOTH arms carry weights
# (w = 1-e for transboundary segments, w = e for domestic ones); reporting
# each arm unweighted and ATO-weighted is what makes the reweighting legible.
#
# This replaces a hand-built table that predated the current sample and the
# move to overlap weights. That table reported 637 domestic segments against
# the 654 used everywhere else, and carried four variables the current
# configuration does not have: segment area, distance to the nearest major
# road, the GAEZ soil/terrain suitability index and TerraClimate PET. Those
# rows are not reconstructed here because the pipeline has no source for them.
# =============================================================================

# Weighted quantiles on the weighted ECDF. With equal weights this reduces to
# the ordinary sample quantile, so both column families use one code path.
wquantile <- function(x, w, probs) {
  ok <- is.finite(x) & is.finite(w) & w > 0
  x <- x[ok]; w <- w[ok]
  if (!length(x)) return(rep(NA_real_, length(probs)))
  o <- order(x); x <- x[o]; w <- w[o]
  cw <- cumsum(w) / sum(w)
  out <- numeric(length(probs))
  for (k in seq_along(probs)) {
    i <- which(cw >= probs[k])[1L]
    out[k] <- if (is.na(i)) x[length(x)] else x[i]
  }
  out
}

mqi <- function(x, w) {
  q <- wquantile(x, w, c(0.25, 0.50, 0.75))
  paste0(fmt(q[2], 3), " [", fmt(q[1], 3), ", ", fmt(q[3], 3), "]")
}

# The segment frame keeps the minimum, SD and range of well-to-border distance
# but not its mean, so that one variable is taken from the well frame here
# rather than added to the cached segment build.
.wf <- fs_wells(cfg) %>%
  group_by(unit_id) %>%
  summarise(D_border = mean(dist_LB_km, na.rm = TRUE), .groups = "drop")
dS <- d %>% left_join(.wf, by = "unit_id")

.sv_var <- c("n", "urbkHaKm2", "CS_max", "prec_mm",
             "beta_0", "D_border", "LB_river")
.sv_lab <- c("$N_w$ observation wells per segment",
             "$UC$ urban cover (kha km$^{-2}$)",
             "$CSI$ crop suitability index (1--10,000)",
             "$PREC$ annual precipitation (mm yr$^{-1}$)",
             "$GWD$ segment mean depletion (mm yr$^{-1}$)",
             "$D_border$ mean well-to-border distance (km)",
             "$P_LBRiv$ share of wells whose nearest border is a river")

.col_nm <- c("Domestic", "Domestic (ATO)", "Transboundary", "Transboundary (ATO)")
.col_tb <- c(0L, 0L, 1L, 1L)
.col_wt <- c(FALSE, TRUE, FALSE, TRUE)

.ess <- function(w) sum(w)^2 / sum(w^2)

.cells <- matrix("", nrow = length(.sv_var) + 2L, ncol = length(.col_nm))
for (j in seq_along(.col_nm)) {
  sub <- dS[dS$TBn == .col_tb[j], , drop = FALSE]
  wj  <- if (.col_wt[j]) sub$w_ato else rep(1, nrow(sub))
  .cells[1L, j] <- as.character(nrow(sub))
  for (i in seq_along(.sv_var))
    .cells[i + 1L, j] <- mqi(sub[[.sv_var[i]]], wj)
  .cells[length(.sv_var) + 2L, j] <-
    if (.col_wt[j]) fmt(.ess(wj), 4) else as.character(nrow(sub))
}

tS1 <- data.frame(
  Variable = c("$N$ aquifer--country segments", .sv_lab,
               "effective sample size (segments)"),
  .cells, stringsAsFactors = FALSE, check.names = FALSE)
names(tS1) <- c("Variable", .col_nm)

# Guard rails: the table must describe the same sample the results do.
stopifnot(nrow(dS) == nrow(d),
          sum(dS$TBn == 1) == sum(d$TBn == 1),
          all(is.finite(dS$w_ato)))
write_pair(tS1, "table_si_wells_sumstats", 3)

say("\nTable S1 written. Nothing from 34/35/36 was needed.\n")
print(as.data.frame(tS1), row.names = FALSE, right = FALSE)
